"""Turn the codeset's small `.set` constants into a C header.

Addresses already come through as linker symbols (gen_slippi_symbols.py); this
is for the structure offsets - MSRB field positions and the like - which module
C code needs as plain numbers and which would otherwise be copied by hand and
drift the moment someone adds a field.

Definitions reference each other in any order, so resolve by repeated passes
until nothing new falls out.
"""
import re, sys, pathlib

# The value runs to the end of the line or to a trailing comment. Requiring
# end-of-line straight after it silently drops every definition that carries a
# comment, which is most of them - and the chain then breaks at the first gap.
SET = re.compile(r'^\s*\.set\s+([A-Za-z_][A-Za-z0-9_]*)\s*,\s*([^#\n]+?)\s*(?:#[^\n]*)?$', re.M)
WORD = re.compile(r'\b([A-Za-z_][A-Za-z0-9_]*)\b')


def collect(sources):
    defs = {}
    for src in sources:
        for m in SET.finditer(pathlib.Path(src).read_text(errors="replace")):
            defs.setdefault(m.group(1), m.group(2).strip())
    return defs


def resolve(defs):
    vals = {}
    while True:
        progress = False
        for name, expr in defs.items():
            if name in vals:
                continue
            if any(w not in vals for w in WORD.findall(expr)
                   if not w.startswith("0x") and not w.isdigit()):
                continue
            try:
                vals[name] = eval(WORD.sub(lambda m: str(vals[m.group(1)]), expr),
                                  {"__builtins__": {}}, {})
                progress = True
            except Exception:
                pass
        if not progress:
            return vals


def main(sources, out, prefixes):
    vals = resolve(collect(sources))
    keep = {k: v for k, v in vals.items()
            if isinstance(v, int) and 0 <= v < 0x10000
            and any(k.startswith(p) for p in prefixes)}
    with open(out, "w") as f:
        f.write("/* Generated by gen_slippi_consts.py -- do not edit. */\n")
        f.write("#ifndef SLIPPI_CONSTS_H\n#define SLIPPI_CONSTS_H\n\n")
        for k, v in sorted(keep.items(), key=lambda kv: (kv[1], kv[0])):
            f.write(f"#define {k} {v}\n")
        f.write("\n#endif\n")
    print(f"{len(keep)} constants -> {out}", file=sys.stderr)
    return keep


if __name__ == "__main__":
    kept = main(sys.argv[1:-1], sys.argv[-1], ("MSRB_", "CSSDT_", "ONLINE_MODE_", "MM_STATE_"))
    for k in ("MSRB_ROSTER", "MSRB_ROSTER_SLOTS", "MSRB_ROSTER_STRIDE",
              "MSRB_ROOM_MODE", "MSRB_SIZE"):
        print(f"  {k:22s} {kept.get(k, 'unresolved')}")
