"""Turn the codeset's `.set NAME,0x8xxxxxxx` lines into linker symbols.

Slippi's injected helpers (FN_EXITransferBuffer, FN_LoadMatchState, ...) live at
fixed addresses in the codeset we build, so module C code can call them by name
the same way it calls Melee's own functions.
"""
import re, sys, pathlib

PAT = re.compile(r"^\s*\.set\s+([A-Za-z_][A-Za-z0-9_]*)\s*,\s*(0x8[0-9a-fA-F]{7})\s*(?:#.*)?$")

def main(sources, out):
    syms = {}
    for src in sources:
        for line in pathlib.Path(src).read_text(errors="replace").splitlines():
            m = PAT.match(line)
            if m:
                syms.setdefault(m.group(1), int(m.group(2), 16))
    with open(out, "w") as f:
        f.write("/* Generated by gen_slippi_symbols.py -- do not edit. */\n")
        for n, a in sorted(syms.items(), key=lambda kv: kv[1]):
            f.write(f"PROVIDE({n} = 0x{a:08X});\n")
    print(f"{len(syms)} codeset symbols -> {out}", file=sys.stderr)

if __name__ == "__main__":
    main(sys.argv[1:-1], sys.argv[-1])
